### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by vtrev** [MinenhleS/BikeRide#1]
@MinenhleS  Try to have consistent naming, your packages are named BikePackage and the other one is FunRidePack, and also the word package after the package name is not needed. The Bike package would be better if it contains the word rides since there are bike rides in there. no UPPERCASE on package names.

![Screenshot from 2019-03-25 10-02-33](https://user-images.githubusercontent.com/32287425/54903793-6629bf00-4ee5-11e9-9faf-41632f6cca9f.png)

**Comment by MinenhleS** [comment]
I've done with naming packages in a proper way.

**Comment by vtrev** [comment]
Sure thing, next issue you just comment and the person who opened the issue
will review and close it, you should only close issues you open. Just one
more thing on the naming, try to name your things in a way that someone
else will understand. The package someriding is confusing.
