### ISSUE TITLE
Test one not testing what it says

### ISSUE THREAD

**Issue by vtrev** [MinenhleS/BikeRide#2]
The method ShouldRunSpecFunRide does not run any ride on the bikes, it is testing for the total count and count for type. How about you make that 2 different tests and add a test for the actual ride?

https://github.com/MinenhleS/BikeRide/blob/master/tests/bicycles/FunRideTest.java#L14-L33

**Comment by MinenhleS** [comment]
I separated tests for specific testing in my fun ride testing class

**Comment by vtrev** [comment]
Nice one, try to do something like that  also for the BicycleTypeTest. From that name the file should contain tests for the type of bicycle. However it shows the testing of bikerides as well. Try to make it that where there is a ride() method you test for the current speeds and where you make bike from spec is where you test if your getter methods return the values you specified in creation of the bicycle. Remember to only test for what the test method says.

**Comment by MinenhleS** [comment]
I tried and fixed that created another class for that test .

**Comment by vtrev** [comment]
Nice one, I'm closing the issue. Just some extra challenge if you are keen,when  testing for the bicycle type, instead of testing using a string like in :assertEquals(roadBikeSpec.getBicycleType().toString(),"RoadBike");

Maybe it would be better to test for the actual type from the BycicleTpes enum.Something  like assertEquals(roadBikeSpec.getBicycleType(),BicycleTypes.ROADBIKE);

**Comment by avermeulen** [comment]
@vtrev this 👍 ! You can add my username to an issue if you want to notify me about it
